[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore erp-escolar.sln"]

[phases.build]
cmds = ["dotnet publish src/ErpEscolar.Api/ErpEscolar.Api.csproj -c Release"]

[start]
cmd = "dotnet src/ErpEscolar.Api/bin/Release/net8.0/publish/ErpEscolar.Api.dll"
